config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  resources :juices
  root to: 'juices#index'
  get '/juices/:id' => 'juices#show' 
  post '/juices/:id' => 'juices#show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/juices/:id" => "juices#show"
  post "/juices/:id" => "juices#show"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/juice.rb
class Juice < ApplicationRecord
    has_many :posts, :dependent => :destroy
    mount_uploader :image, ImageUploader
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, :dependent => :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/juices_controller.rb
class JuicesController < ApplicationController
  before_action :set_juice, only: [:show, :edit, :update, :destroy]

  # GET /juices
  # GET /juices.json
  def index
    if params[:hoge]
        @juices = Juice.where(name: params[:hoge])
      else
        # @juices = Juice.find_by_sql("SELECT * FROM juices WHERE id = 2")
        @juices = Juice.all
    end
    
  end

  # GET /juices/1
  # GET /juices/1.json
  def show
    if params[:user_id] && params[:juice_id]
      data = Post.new(user_id: params[:user_id], juice_id: params[:juice_id])
      data.save
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /juices/new
  def new
    @juice = Juice.new
  end

  # GET /juices/1/edit
  def edit
  end

  # POST /juices
  # POST /juices.json
  def create
    @juice = Juice.new(juice_params)

    respond_to do |format|
      if @juice.save
        format.html { redirect_to @juice, notice: 'Juice was successfully created.' }
        format.json { render :show, status: :created, location: @juice }
      else
        format.html { render :new }
        format.json { render json: @juice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /juices/1
  # PATCH/PUT /juices/1.json
  def update
    respond_to do |format|
      if @juice.update(juice_params)
        format.html { redirect_to @juice, notice: 'Juice was successfully updated.' }
        format.json { render :show, status: :ok, location: @juice }
      else
        format.html { render :edit }
        format.json { render json: @juice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /juices/1
  # DELETE /juices/1.json
  def destroy
    @juice.destroy
    respond_to do |format|
      format.html { redirect_to juices_url, notice: 'Juice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_juice
      @juice = Juice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def juice_params
      params.require(:juice).permit(:name, :capacity, :price, :image, :user_id, :juice_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :juice_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/juices_helper.rb
module JuicesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/juices/_form.html.erb
<%= form_with(model: juice, local: true) do |form| %>
  <% if juice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(juice.errors.count, "error") %> prohibited this juice from being saved:</h2>

      <ul>
      <% juice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :capacity %>
    <%= form.number_field :capacity, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :image,"画像" %>
    <br>
    <%= form.file_field :image %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/juices/edit.html.erb
<div class="col-md-6">
<h1>Editing Juice</h1>

<%= render 'form', juice: @juice %>

<%= link_to 'Show', @juice %> |
<%= link_to 'Back', juices_path %>
</div>

app/views/juices/index.html.erb
<p id="notice"><%= notice %></p>
<div class="col-md-10 col-xs-12">
<h1>JUICES</h1><hr>


    <% @juices.each do |juice| %>
      <div class="col-md-3 add_left">
      <%= image_tag juice.image.to_s, style: "width: 100%;" %>       
        <h2><%= juice.name %></h2>
        <p><%= juice.capacity %>
        <%= juice.price %></p>
        <p><%= link_to 'Show', juice, class: "btn btn-primary font_no_iro" %>
        <%= link_to 'Edit', edit_juice_path(juice), class: "btn btn-success" %>
        <%= link_to 'Destroy', juice, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></p>
        
      </div>
    <% end %>
  

<br>

<% link_to 'New Juice', new_juice_path, class: "btn btn-info" %>
</div>

<div class="col-md-2 col-xs-12">
<img src="/top1.jpg" alt="バナー画像" class="img-thumbnail"><br><br>
<img src="/top2.jpg" alt="バナー画像" class="img-thumbnail"><br><br>
  <div class="list-group">
    <a href="#" class="list-group-item active">テキスト</a>
    <a href="#" class="list-group-item">テキスト</a>
    <a href="#" class="list-group-item">テキスト</a>
    <a href="#" class="list-group-item">テキスト</a>
  </div>
</div>

app/views/juices/new.html.erb
<div class="col-md-6">
<h1>New Juice</h1>

<%= render 'form', juice: @juice %>

<%= link_to 'Back', juices_path %>
</div>

app/views/juices/show.html.erb
<div class="col-md-12">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @juice.name %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @juice.capacity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @juice.price %>
</p>

<%= form_tag(url_for(:action => 'show'), :remote => true) do %>
<%= hidden_field_tag :user_id, current_user.id %>
<%= hidden_field_tag :juice_id, @juice.id %>
<!-- unless: いいねされてなかったらボタン表示 -->
  　　<% unless Post.find_by(user_id: current_user.id, juice_id: @juice.id) %>
  <h1><%= submit_tag "👍" %></h1>
  <% else %>
  <h1>👍</h1>
  　　<% end %>
  
  <% end %>

<%= current_user.email %>

<%= link_to 'Edit', edit_juice_path(@juice) %> |
<%= link_to 'Back', juices_path %>
</div>

app/views/juices/show.js.erb
$('h1').html("👍");

app/views/layouts/_slider.html.erb
<!--スライダー-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick-theme.css">
<div class='slick' style="padding: 50px;">
<div class='slick-item'>
<div><h3><a href="#"><img src="/top1.jpg" width="100%" height="100%"></a></h3></div>
<div><h3><a href="#"><img src="/top2.jpg" width="100%" height="100%"></a></h3></div>
<div><h3><a href="#"><img src="/top3.jpg" width="100%" height="100%"></a></h3></div>
</div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.js"></script>


<!--/スライダー-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <title>Startapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- jquery -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="/css/style.css">
     </head>

  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
  <ul class="navbar-nav">
  <li class="nav-item active">
  <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
  </li>
  <li class="nav-item">
  <a class="nav-link" href="#">Features</a>
  </li>
  <li class="nav-item">
  <a class="nav-link" href="#">Pricing</a>
  </li>
  <li class="nav-item">
  <%= link_to 'New Juice', new_juice_path, class: "nav-link" %>
  </li>
  <% if user_signed_in? %>
<li class="nav-item"><%= link_to 'プロフィール変更', edit_user_registration_path, class: "nav-link disabled" %></li>
<li class="nav-item"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "nav-link disabled" %></li>
<% else %>
<li class="nav-item"><%= link_to 'サインアップ', new_user_registration_path, class: "nav-link disabled" %></li>
<li class="nav-item"><%= link_to 'ログイン', new_user_session_path, class: "nav-link disabled" %></li>
<% end %>

<%= form_tag(juices_path, method: "get", class: "form-inline") do %>
  <%= text_field_tag :hoge, "" ,class: "form-control mr-sm-2", placeholder: "hoge" %>
<%= submit_tag '検索', class: "btn btn-outline-success my-2 my-sm-0" %>
<% end %>

  </ul>
  </div>
  </nav>

 
<p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<div class="container">
<%= render partial: 'layouts/slider' %>
</div>
  <div class="container">
  <div class="row">
    <%= yield %>
    </div>
  </div>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js" integrity="sha384-pjaaA8dDz/5BgdFUPX6M/9SUZv4d12SUPF0axWc+VRZkx5xU3daN+lYb49+Ax+Tl" crossorigin="anonymous"></script>
    <hr><%= p params %>
    </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :juice_id %>
    <%= form.number_field :juice_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Juice</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.user_id %></td>
        <td><%= post.juice_id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @post.user_id %>
</p>

<p>
  <strong>Juice:</strong>
  <%= @post.juice_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>